### PR TITLE
docs: add semver section

### PR DESCRIPTION
**Pull request by kentcdodds**
Addresses comments in #27

### CODE REVIEW

**Comment by kentcdodds** [comment]
May not be necessary to merge this until we setup auto-releases.

**Comment by jonathanewerner** [comment]
On hold till we use auto-release.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 811e3686a1d1f12506811969efce7299d6e95395
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/stevemao/conventional-changelog-angular/blob/master/convention.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d2312f6fa97a4973dbfe827ab1dfcdf657e88724
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/stevemao/conventional-changelog-angular/blob/master/convention.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8c417b593801131ca110eff7f947f31bb9e7f484
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/stevemao/conventional-changelog-angular/blob/master/convention.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 70fce662f9c5a96a4ae90d169e7582c363169120
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/stevemao/conventional-changelog-angular/blob/master/convention.md

---

This message was auto-generated by https://gitcop.com

**Pull request closed without merging**
